### PR TITLE
new M2 model and Kang analysis

### PR DESCRIPTION
**Pull request by nrosed**
In this PR I introduce the M2 model and experiments on the Kang dataset

### Kang Data
The data was retreived using  the SeuratData package in R and then translated into an AnnData object to be read into python,
Notebook for SeuratData analysis of Kang data (names ifnb in SeuratData): https://satijalab.org/seurat/articles/integration_introduction.html
Seurat Disk was used for conversion between h5Seurat and AnnData: https://mojaveazure.github.io/seurat-disk/articles/convert-anndata.html

Kang data is originally from here: 
Kang, Hyun Min, et al. "Multiplexed droplet single-cell RNA-sequencing using natural genetic variation." Nature biotechnology 36.1 (2018): 89-94.

### M2 Model
This model directly inserts the cell type proportions as a section of the latent code when available and simultaneously trains a cell-type proportion predictor. When the cell-type proportions are not available, the proportion predictor is used to generate the relevant section in the latent code.

This PR also includes a comparison between 

1. M1 model -> auxiliary loss on latent code `exploratory_experiments/pbmc1a_ssDIVA.ipynb`
3. M1_M2 hybrid `exploratory_experiments/pbmc1a_ssDIVA_M1M2.ipynb`
4. Basic NN cell-type predictor (exploratory_experiments/pbmc1a_simple_pred.ipynb)

### Code to be reviewed

There is some new code and some code with only minor changes. Below I provide a list of files I would like to be reviewed. You can of course review them all, but the files listed below have highest priority.

- New model -- M2
    - model code: `diva/diva_m2.py`
- PBMC Experiments with M2
    - PBMC M2 experiment: `evaluation_experiments/pbmc/pbmc_experiment_M2.ipynb`
- Kang Data
    - `evaluation_experiments/kang/kang_buddiM2_train.py`
    - `evaluation_experiments/kang/kang_buddiM2_train.sh`
    - `evaluation_experiments/kang/kang_translate_to_cibersort.py`
    - `evaluation_experiments/kang/kang_translate_to_cibersort.sh`
    - `sc_preprocessing/0_qc_notebooks/scanpy_analysis_kang.ipynb`
    - `sc_preprocessing/2_make_pseudobulks/scanpy_sc_preprocess_kang.ipynb`
    - `evaluation_experiments/kang/kang_experiment_M2.ipynb`

### CODE REVIEW

**Review by ivichadriana — COMMENTED** [review]
I just added a couple of questions about some lines you might want to double check. If not, everything looks awesome and ready to merge!

**Review by ivichadriana — COMMENTED** [review]
Hopefully this shows the comments I made. Everything looks fine, just want to double check some things are on purpose.

**Review by ivichadriana — APPROVED** [review]
Added 4 comments; just saw some imports down in the file and wonder if they are expected to be there vs. at the top. Everything else looks good and ready to merge.

**Comment by nrosed** [comment]
<p>good point, moved it to the top in</p><p><a href="https://github.com/greenelab/sc_bulk_ood/pull/10/commits/777aada29ab2ae6ec567775dc2e59d0849e30ed5" target="_blank">https://github.com/greenelab/sc_bulk_ood/pull/10/commits/777aada29ab2ae6ec567775dc2e59d0849e30ed5</a></p><p><a href="https://github.com/greenelab/sc_bulk_ood/pull/10/commits/e6a3b6fbaf4ab8968b7e8d7b67019c4d6ada97f3" target="_blank">https://github.com/greenelab/sc_bulk_ood/pull/10/commits/e6a3b6fbaf4ab8968b7e8d7b67019c4d6ada97f3</a></p>

---

 <a href='https://app.reviewnb.com/greenelab/sc_bulk_ood/pull/10/discussion/#comment-1408991012'>View entire conversation</a> on ReviewNB<div id="RAICReplyForNotification-ReviewNBCommentContext-DoNotDelete"></div>

**Pull request merged**
